### ISSUE TITLE
Re-add web/static to deploy

### ISSUE THREAD

**Issue by Lohrer** [micro-nova/AmpliPi#621]
In commit 725ccf0e0da7db960f8a2a23a60ec869d5eec427 `web/static` was removed from deploys/releases. This appears to be a necessary directory, doing a deploy to a clean Pi gives the log:

```txt
Jan 12 08:14:47 amplipi197 systemd[610]: Started Amplipi Home Audio System.
Jan 12 08:14:50 amplipi197 authbind[14531]: Traceback (most recent call last):
Jan 12 08:14:50 amplipi197 authbind[14531]:   File "/usr/lib/python3.7/runpy.py", line 193, in _run_module_as_main
Jan 12 08:14:50 amplipi197 authbind[14531]:     "__main__", mod_spec)
Jan 12 08:14:50 amplipi197 authbind[14531]:   File "/usr/lib/python3.7/runpy.py", line 85, in _run_code
Jan 12 08:14:50 amplipi197 authbind[14531]:     exec(code, run_globals)
Jan 12 08:14:50 amplipi197 authbind[14531]:   File "/home/pi/amplipi-dev/venv/lib/python3.7/site-packages/uvicorn/__main__.py", line 4, in <module>
Jan 12 08:14:50 amplipi197 authbind[14531]:     uvicorn.main()
Jan 12 08:14:50 amplipi197 authbind[14531]:   File "/home/pi/amplipi-dev/venv/lib/python3.7/site-packages/click/core.py", line 1157, in __call__
Jan 12 08:14:50 amplipi197 authbind[14531]:     return self.main(*args, **kwargs)
Jan 12 08:14:50 amplipi197 authbind[14531]:   File "/home/pi/amplipi-dev/venv/lib/python3.7/site-packages/click/core.py", line 1078, in main
Jan 12 08:14:50 amplipi197 authbind[14531]:     rv = self.invoke(ctx)
Jan 12 08:14:50 amplipi197 authbind[14531]:   File "/home/pi/amplipi-dev/venv/lib/python3.7/site-packages/click/core.py", line 1434, in invoke
Jan 12 08:14:50 amplipi197 authbind[14531]:     return ctx.invoke(self.callback, **ctx.params)
Jan 12 08:14:50 amplipi197 authbind[14531]:   File "/home/pi/amplipi-dev/venv/lib/python3.7/site-packages/click/core.py", line 783, in invoke
Jan 12 08:14:50 amplipi197 authbind[14531]:     return __callback(*args, **kwargs)
Jan 12 08:14:50 amplipi197 authbind[14531]:   File "/home/pi/amplipi-dev/venv/lib/python3.7/site-packages/uvicorn/main.py", line 449, in main
Jan 12 08:14:50 amplipi197 authbind[14531]:     h11_max_incomplete_event_size=h11_max_incomplete_event_size,
Jan 12 08:14:50 amplipi197 authbind[14531]:   File "/home/pi/amplipi-dev/venv/lib/python3.7/site-packages/uvicorn/main.py", line 569, in run
Jan 12 08:14:50 amplipi197 authbind[14531]:     server.run()
Jan 12 08:14:50 amplipi197 authbind[14531]:   File "/home/pi/amplipi-dev/venv/lib/python3.7/site-packages/uvicorn/server.py", line 60, in run
Jan 12 08:14:50 amplipi197 authbind[14531]:     return asyncio.run(self.serve(sockets=sockets))
Jan 12 08:14:50 amplipi197 authbind[14531]:   File "/usr/lib/python3.7/asyncio/runners.py", line 43, in run
Jan 12 08:14:50 amplipi197 authbind[14531]:     return loop.run_until_complete(main)
Jan 12 08:14:50 amplipi197 authbind[14531]:   File "/usr/lib/python3.7/asyncio/base_events.py", line 584, in run_until_complete
Jan 12 08:14:50 amplipi197 authbind[14531]:     return future.result()
Jan 12 08:14:50 amplipi197 authbind[14531]:   File "/home/pi/amplipi-dev/venv/lib/python3.7/site-packages/uvicorn/server.py", line 67, in serve
Jan 12 08:14:50 amplipi197 authbind[14531]:     config.load()
Jan 12 08:14:50 amplipi197 authbind[14531]:   File "/home/pi/amplipi-dev/venv/lib/python3.7/site-packages/uvicorn/config.py", line 477, in load
Jan 12 08:14:50 amplipi197 authbind[14531]:     self.loaded_app = import_from_string(self.app)
Jan 12 08:14:50 amplipi197 authbind[14531]:   File "/home/pi/amplipi-dev/venv/lib/python3.7/site-packages/uvicorn/importer.py", line 21, in import_from_string
Jan 12 08:14:50 amplipi197 authbind[14531]:     module = importlib.import_module(module_str)
Jan 12 08:14:50 amplipi197 authbind[14531]:   File "/usr/lib/python3.7/importlib/__init__.py", line 127, in import_module
Jan 12 08:14:50 amplipi197 authbind[14531]:     return _bootstrap._gcd_import(name[level:], package, level)
Jan 12 08:14:50 amplipi197 authbind[14531]:   File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
Jan 12 08:14:50 amplipi197 authbind[14531]:   File "<frozen importlib._bootstrap>", line 983, in _find_and_load
Jan 12 08:14:50 amplipi197 authbind[14531]:   File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
Jan 12 08:14:50 amplipi197 authbind[14531]:   File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
Jan 12 08:14:50 amplipi197 authbind[14531]:   File "<frozen importlib._bootstrap_external>", line 728, in exec_module
Jan 12 08:14:50 amplipi197 authbind[14531]:   File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
Jan 12 08:14:50 amplipi197 authbind[14531]:   File "./amplipi/asgi.py", line 27, in <module>
Jan 12 08:14:50 amplipi197 authbind[14531]:     import amplipi.app
Jan 12 08:14:50 amplipi197 authbind[14531]:   File "./amplipi/app.py", line 72, in <module>
Jan 12 08:14:50 amplipi197 authbind[14531]:     app.mount("/static", StaticFiles(directory=STATIC_DIR), name="static")
Jan 12 08:14:50 amplipi197 authbind[14531]:   File "/home/pi/amplipi-dev/venv/lib/python3.7/site-packages/starlette/staticfiles.py", line 57, in __init__
Jan 12 08:14:50 amplipi197 authbind[14531]:     raise RuntimeError(f"Directory '{directory}' does not exist")
```

**Comment by rtertiaer** [comment]
I'm pretty sure I fixed this in #633 .
